### PR TITLE
[CI] Adapting Dockerfile to humble

### PR DESCRIPTION
**Pull request by orensbruli**
Docker files and repos modified to run in humble.

### CODE REVIEW

**Comment by Yadunund** [comment]
There is already an effort to migrate to humble here https://github.com/open-rmf/rmf/pull/165 but a blocker seems to be related to `libceres`.

**Comment by orensbruli** [comment]
I have also looked into that PRand also investigated the problem and commented in this issue https://github.com/open-rmf/rmf_traffic_editor/issues/439
I think that while [nightly](https://github.com/open-rmf/rmf/pull/165/files#diff-e79198339eb3fcc6974b6912e52526068eab3b7952ed67d03276479a235eb58eR14) is using `ros-tooling/setup-ros@v0.3` and that action installs `libc++-dev` by default, we are gonna get this conflict until libgoogle-glog-dev is updated to `libunwind-14-dev` or we remove the `libc++-dev` from `ros-tooling/setup-ros@v0.3` (related: https://github.com/ros-tooling/setup-ros/issues/506)
My suggestion would be to proceed with updating the two files in this PR and then keep the blocker only for the `nightly.yaml` file. 
What do you think?

**Comment by Yadunund** [comment]
I see thanks for explaining that.
Would it be more streamlined if we merge this PR into the `humble-image` branch first? So target `humble-image` and not `main`.

**Comment by orensbruli** [comment]
> I see thanks for explaining that. Would it be more streamlined if we merge this PR into the `humble-image` branch first? So target `humble-image` and not `main`.

True.
Then I think that my modifications to the Dockerfile should go to https://github.com/open-rmf/rmf_deployment_template/blob/main/rmf/rmf.Dockerfile  right?

**Pull request closed without merging**
